# Goal definition
# Note: gimbal centre is 0. Pitch fully up = 90, fully down = -90.
# Yaw (when looking forward over the gimbal): fully right = 90, fully left = -90.
int16 pitch
int16 yaw
---
# Result definition
int16 pitch
int16 yaw
